from pyjop import *

SimEnv.connect()

env = SimEnvManager.first()
env.reset()
piano = Piano.first()

def play_moonlight_sonata():
    # Main theme
    for _ in range(2):
        piano.play_chord(["C#3", "G#3", "C#4"])
        sleep(0.08)
        piano.play_note_in_octave("G#", 3)
        sleep(0.08)
        piano.play_note_in_octave("C#", 4)
        sleep(0.08)
        piano.play_note_in_octave("E", 4)
        sleep(0.08)
        piano.play_note_in_octave("G#", 3)
        sleep(0.08)
        piano.play_note_in_octave("C#", 4)
        sleep(0.08)
        piano.play_note_in_octave("E", 4)
        sleep(0.08)
        piano.play_note_in_octave("G#", 3)
        sleep(0.08)
        piano.play_note_in_octave("C#", 4)
        sleep(0.08)
        piano.play_note_in_octave("E", 4)
        sleep(0.08)

        piano.play_chord(["B2", "F#3", "B3"])
        sleep(0.08)
        piano.play_note_in_octave("F#", 3)
        sleep(0.08)
        piano.play_note_in_octave("B", 3)
        sleep(0.08)
        piano.play_note_in_octave("D#", 4)
        sleep(0.08)
        piano.play_note_in_octave("F#", 3)
        sleep(0.08)
        piano.play_note_in_octave("B", 3)
        sleep(0.08)
        piano.play_note_in_octave("D#", 4)
        sleep(0.08)
        piano.play_note_in_octave("F#", 3)
        sleep(0.08)
        piano.play_note_in_octave("B", 3)
        sleep(0.08)
        piano.play_note_in_octave("D#", 4)
        sleep(0.08)

    # Second part
    piano.play_chord(["A2", "E3", "A3"])
    sleep(0.08)
    piano.play_note_in_octave("E", 3)
    sleep(0.08)
    piano.play_note_in_octave("A", 3)
    sleep(0.08)
    piano.play_note_in_octave("C#", 4)
    sleep(0.08)
    piano.play_note_in_octave("E", 3)
    sleep(0.08)
    piano.play_note_in_octave("A", 3)
    sleep(0.08)
    piano.play_note_in_octave("C#", 4)
    sleep(0.08)
    piano.play_note_in_octave("E", 3)
    sleep(0.08)
    piano.play_note_in_octave("A", 3)
    sleep(0.08)
    piano.play_note_in_octave("C#", 4)
    sleep(0.08)

    piano.play_chord(["G#2", "E3", "G#3"])
    sleep(0.08)
    piano.play_note_in_octave("E", 3)
    sleep(0.08)
    piano.play_note_in_octave("G#", 3)
    sleep(0.08)
    piano.play_note_in_octave("C#", 4)
    sleep(0.08)
    piano.play_note_in_octave("E", 3)
    sleep(0.08)
    piano.play_note_in_octave("G#", 3)
    sleep(0.08)
    piano.play_note_in_octave("C#", 4)
    sleep(0.08)
    piano.play_note_in_octave("E", 3)
    sleep(0.08)
    piano.play_note_in_octave("G#", 3)
    sleep(0.08)
    piano.play_note_in_octave("C#", 4)
    sleep(0.08)

while SimEnv.run_main():
    play_moonlight_sonata()

SimEnv.disconnect()